name: Build Staging
on:
  push:
    branchs:
      - '*'
      - '!prod-beta'
      - '!prod-stable'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test --passWithNoTests
      - name: Build
        run: npm run build:staging --if-present
      # store the build files into the cache
      - name: Cache Build
        uses: actions/cache@v2
        id: restore-build-staging
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}/staging
