name: Deploy Prod Stable
on:
  workflow_run:
    workflows: ['Build']
    branches: [prod-stable]
    types:
      - completed
env:
  TOKEN: ${{ secrets.TOKEN }}
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  SOURCE_REPO: "RedHatInsights/acs-ui"
  SOURCE_BRANCH: ${{ github.ref_name }}
  DEPLOY_URL: "github.com/RedHatInsights/acs-ui-build"
  WORKSPACE: ${{ github.workspace }}
  GIT_USERNAME: "Github Action"
  GIT_EMAIL: "actions@github.com"
jobs:
  deploy-prod-stable:
    # only run after the build workflow completes
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      # restore the build files from cache
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
      - name: Checkout RedHatInsights/acs-ui-build repo and push build files from acs-ui
        run: |
          bash ${{ github.workspace }}/.github/scripts/deploy.sh
        env:
          DEPLOY_BRANCH: "prod-stable"